@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 17 17:18:29 +0100 2024
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FULL_QAM_TX_tb_behav -key {Behavioral:sim_1:Functional:FULL_QAM_TX_tb} -tclbatch FULL_QAM_TX_tb.tcl -protoinst "protoinst_files/FULL_QAM_TX.protoinst" -protoinst "protoinst_files/XADC_FIFO.protoinst" -protoinst "protoinst_files/DDS_MULT_ADDER.protoinst" -protoinst "protoinst_files/CLOCKS.protoinst" -protoinst "protoinst_files/CLOCKS_inst_0.protoinst" -protoinst "protoinst_files/DDS_MULT_ADDER_inst_0.protoinst" -protoinst "protoinst_files/XADC_FIFO_inst_0.protoinst" -view C:/Users/nicol/Documents/GitHub/tx-16-QAM/prueba_xadc_tb_behav.wcfg -log simulate.log"
call xsim  FULL_QAM_TX_tb_behav -key {Behavioral:sim_1:Functional:FULL_QAM_TX_tb} -tclbatch FULL_QAM_TX_tb.tcl -protoinst "protoinst_files/FULL_QAM_TX.protoinst" -protoinst "protoinst_files/XADC_FIFO.protoinst" -protoinst "protoinst_files/DDS_MULT_ADDER.protoinst" -protoinst "protoinst_files/CLOCKS.protoinst" -protoinst "protoinst_files/CLOCKS_inst_0.protoinst" -protoinst "protoinst_files/DDS_MULT_ADDER_inst_0.protoinst" -protoinst "protoinst_files/XADC_FIFO_inst_0.protoinst" -view C:/Users/nicol/Documents/GitHub/tx-16-QAM/prueba_xadc_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
